<a href="https://colab.research.google.com/github/MatrixAwakens69/pytorch-ml-dl/blob/main/00_pytorch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [18]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.0+cu121


## Introduction to Tensors

## Creating tensors

In [19]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [48]:
scalar.ndim, scalar.item()

(0, 10)

In [22]:
vector = torch.tensor([5, 5])
vector

tensor([5, 5])

In [47]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [26]:
MATRIX = torch.tensor([[4,5],[6,7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [46]:
 MATRIX.ndim, MATRIX.shape, MATRIX[1]

(2, torch.Size([2, 2]), tensor([6, 7]))

In [30]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,6,8]],[[4,5,6],
                                  [7,8,9],
                                  [1,3,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 6, 8]],

        [[4, 5, 6],
         [7, 8, 9],
         [1, 3, 5]]])

In [44]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([2, 3, 3]))

In [45]:
TENSOR[1], TENSOR[1][1]

(tensor([[4, 5, 6],
         [7, 8, 9],
         [1, 3, 5]]),
 tensor([7, 8, 9]))

### Random Tensors

In [43]:
random_tensor = torch.rand(3, 4, 5)
random_tensor, random_tensor.ndim

(tensor([[[0.4159, 0.9796, 0.0511, 0.7450, 0.0301],
          [0.2545, 0.4825, 0.2810, 0.2758, 0.6010],
          [0.0345, 0.4578, 0.4196, 0.9935, 0.0278],
          [0.7737, 0.9595, 0.8604, 0.9175, 0.4936]],
 
         [[0.1827, 0.8846, 0.8793, 0.8452, 0.1304],
          [0.8872, 0.5594, 0.2717, 0.0451, 0.9378],
          [0.7591, 0.1330, 0.9894, 0.7927, 0.6355],
          [0.5384, 0.4077, 0.4804, 0.4649, 0.2907]],
 
         [[0.7229, 0.2283, 0.1576, 0.5435, 0.3258],
          [0.4104, 0.3247, 0.0251, 0.5219, 0.3095],
          [0.6965, 0.2197, 0.1924, 0.0285, 0.3232],
          [0.8098, 0.4048, 0.7034, 0.6394, 0.6804]]]),
 3)

In [49]:
random_image_tensor = torch.rand(size=(3, 256, 256))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 256, 256]), 3)

In [53]:
another_random_tensor = torch.rand(5, 8, 8)
another_random_tensor

tensor([[[0.0409, 0.4352, 0.7319, 0.1869, 0.9718, 0.6334, 0.2719, 0.3601],
         [0.8696, 0.5178, 0.3591, 0.4731, 0.3602, 0.8595, 0.0856, 0.1400],
         [0.1881, 0.2567, 0.8386, 0.1962, 0.0155, 0.2283, 0.1614, 0.0639],
         [0.3887, 0.6623, 0.7881, 0.8076, 0.7442, 0.5155, 0.6964, 0.5879],
         [0.6752, 0.9743, 0.6046, 0.0081, 0.5945, 0.4727, 0.8535, 0.6609],
         [0.0692, 0.9642, 0.2907, 0.0911, 0.1288, 0.0623, 0.0113, 0.2721],
         [0.1256, 0.4769, 0.2092, 0.5766, 0.1796, 0.2464, 0.0158, 0.9319],
         [0.8309, 0.5830, 0.5122, 0.6752, 0.6997, 0.2284, 0.7669, 0.5526]],

        [[0.0795, 0.7975, 0.3408, 0.6503, 0.6635, 0.4040, 0.1053, 0.1792],
         [0.0595, 0.2845, 0.5768, 0.6524, 0.0649, 0.3246, 0.1621, 0.5632],
         [0.7418, 0.0711, 0.7917, 0.6804, 0.5535, 0.8685, 0.8906, 0.2312],
         [0.3336, 0.1702, 0.6503, 0.8276, 0.3015, 0.8738, 0.6972, 0.6770],
         [0.7283, 0.8407, 0.5315, 0.2313, 0.8497, 0.0818, 0.5543, 0.4324],
         [0.7433, 0.292

In [55]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [56]:
one = torch.ones(3, 4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of Tensors

In [60]:
three_fifteen = torch.arange(3, 150, 4)
three_fifteen

tensor([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,  55,
         59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103, 107, 111,
        115, 119, 123, 127, 131, 135, 139, 143, 147])

In [61]:
some_zeroes = torch.zeros_like(three_fifteen)
some_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes