<a href="https://colab.research.google.com/github/MatrixAwakens69/pytorch-ml-dl/blob/main/00_pytorch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.0+cu121


## Introduction to Tensors

## Creating tensors

In [4]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [5]:
scalar.ndim, scalar.item()

(0, 10)

In [6]:
vector = torch.tensor([5, 5])
vector

tensor([5, 5])

In [7]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [8]:
MATRIX = torch.tensor([[4,5],[6,7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [9]:
 MATRIX.ndim, MATRIX.shape, MATRIX[1]

(2, torch.Size([2, 2]), tensor([6, 7]))

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [4,6,8]],[[4,5,6],
                                  [7,8,9],
                                  [1,3,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [4, 6, 8]],

        [[4, 5, 6],
         [7, 8, 9],
         [1, 3, 5]]])

In [14]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([2, 3, 3]))

In [15]:
TENSOR[1], TENSOR[1][1]

(tensor([[4, 5, 6],
         [7, 8, 9],
         [1, 3, 5]]),
 tensor([7, 8, 9]))

### Random Tensors

In [16]:
random_tensor = torch.rand(3, 4, 5)
random_tensor, random_tensor.ndim

(tensor([[[0.6010, 0.4459, 0.4766, 0.1349, 0.5312],
          [0.8763, 0.0135, 0.1911, 0.9405, 0.1015],
          [0.6038, 0.1973, 0.3774, 0.5700, 0.4986],
          [0.1910, 0.4517, 0.5541, 0.1716, 0.3575]],
 
         [[0.9240, 0.5253, 0.7203, 0.6269, 0.5765],
          [0.2221, 0.8024, 0.3504, 0.1694, 0.1005],
          [0.9849, 0.0754, 0.8948, 0.1814, 0.6812],
          [0.1409, 0.8638, 0.7460, 0.9786, 0.4769]],
 
         [[0.1821, 0.7498, 0.1225, 0.2653, 0.7101],
          [0.3872, 0.1112, 0.9677, 0.0027, 0.6942],
          [0.2992, 0.7196, 0.2852, 0.9939, 0.3151],
          [0.5937, 0.5171, 0.5221, 0.3761, 0.1716]]]),
 3)

In [17]:
random_image_tensor = torch.rand(size=(3, 256, 256))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 256, 256]), 3)

In [39]:
another_random_tensor = torch.rand(5, 8, 8)
another_random_tensor

tensor([[[0.5743, 0.3596, 0.7142, 0.7823, 0.8462, 0.6738, 0.1610, 0.6472],
         [0.6833, 0.0107, 0.6688, 0.0489, 0.3788, 0.4917, 0.4237, 0.1908],
         [0.8944, 0.7738, 0.6890, 0.2011, 0.8452, 0.9159, 0.9905, 0.5076],
         [0.8331, 0.8950, 0.2534, 0.8911, 0.2759, 0.4257, 0.9277, 0.7788],
         [0.1697, 0.8468, 0.3628, 0.0181, 0.7991, 0.3021, 0.9087, 0.1087],
         [0.0049, 0.6406, 0.4906, 0.5425, 0.0742, 0.3830, 0.7585, 0.2709],
         [0.3350, 0.5690, 0.8227, 0.6909, 0.9307, 0.2575, 0.0871, 0.4789],
         [0.7923, 0.6806, 0.3083, 0.3146, 0.2952, 0.7451, 0.1165, 0.0426]],

        [[0.4245, 0.8023, 0.8595, 0.7267, 0.2069, 0.9176, 0.6355, 0.4158],
         [0.9675, 0.4895, 0.0666, 0.2537, 0.2400, 0.7655, 0.1147, 0.5019],
         [0.0814, 0.9449, 0.0084, 0.7280, 0.9975, 0.8813, 0.1674, 0.8623],
         [0.4453, 0.8096, 0.3730, 0.9405, 0.1686, 0.3447, 0.6438, 0.8086],
         [0.5842, 0.5883, 0.5146, 0.3937, 0.5172, 0.3504, 0.7837, 0.7727],
         [0.8304, 0.559

In [26]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
one = torch.ones(3, 4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Range of Tensors

In [28]:
three_fifteen = torch.arange(3, 150, 4)
three_fifteen

tensor([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,  55,
         59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103, 107, 111,
        115, 119, 123, 127, 131, 135, 139, 143, 147])

In [29]:
some_zeroes = torch.zeros_like(three_fifteen)
some_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes