<a href="https://colab.research.google.com/github/MatrixAwakens69/pytorch-ml-dl/blob/main/00_pytorch_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.PyTorch Fundamentals

Resource: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [18]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.0+cu121


## Introduction to Tensors

## Creating tensors

In [19]:
# scalar
scalar = torch.tensor(10)
scalar

tensor(10)

In [20]:
scalar.ndim

0

In [21]:
scalar.item()

10

In [22]:
vector = torch.tensor([5, 5])
vector

tensor([5, 5])

In [23]:
vector.ndim

1

In [24]:
vector.shape

torch.Size([2])

In [26]:
MATRIX = torch.tensor([[4,5],[6,7]])
MATRIX

tensor([[4, 5],
        [6, 7]])

In [27]:
 MATRIX.ndim

2

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
MATRIX[1]

tensor([6, 7])